### ISSUE TITLE
Unable to run on windows | unable to create a successful session

### ISSUE THREAD

**Issue by venkata16sidhartha** [SubGlitch1/OSRipper#10]
I have ran the program in kali 2022.1, with all packages full updated. It generated exe, but when i run it in windows i get "This app cant run on your PC. To find a full version for your PC...." popup. Additionally, if i create  exe by myself, by modifying the ip from 0.0.0.0 to my kali ip in ocr file(obfuscate it and create exe using same command), it runs but shell dosent popup, the obfuscated py file is dropping shell, but exe isnt either running or not dropping shell.

For shell that is being created im getting: Meterpreter session <> is not valid will be closed.(This is for the exe i create, m creating exe from obfuscated py code in windows, hence its atleast running, idk why its not creating session.)

Ive tried this on option 1. further more, initial meu is giving 3 options in one kali pc, and another is giving 5 options. could you help on that as well.

**Comment by SubGlitch1** [comment]
you cannot compile a .exe on linux just like you cannot compile a Unix executable on windows.
You have to compile on the same OS type that you want it to run on.

**Comment by SubGlitch1** [comment]
also before trying again please clone again as there are some major updates

**Comment by venkata16sidhartha** [comment]
Still the name with new update:
I ran the main.py in kali, then ran pyinstaller, same command that is there in main.py in windows on the ocr_or.py file, then i ran created windows, but this is the issue.
![Capture](https://user-images.githubusercontent.com/46317898/166109107-2189ed4b-4aa8-4be9-b20e-d4b1b591153b.PNG)

**Comment by venkata16sidhartha** [comment]
And the same if i compile and do everything in windows:
![image](https://user-images.githubusercontent.com/46317898/166109257-6e6240d6-0d87-416e-9cf7-361fb3939f8a.png)
this is for option 1.

**Comment by SubGlitch1** [comment]
that is interesting. Can you try with option 2 while i take a look at this and let me know how your results are there

**Comment by venkata16sidhartha** [comment]
While you take a look, please try from 2 different systems, ie, exe should run in 1 system, and msf in another, if i run py file in same system as that of msf, im getting a stable shell, the same py file if i run in another system ,different ip same subnet, im getting the above images.

**Comment by venkata16sidhartha** [comment]
For option 2, im getting this error, when i compile in windows, and run the exe
![image](https://user-images.githubusercontent.com/46317898/166109653-92bd590f-c01b-4008-89ad-0c4d9d7bd3d8.png)

**Comment by SubGlitch1** [comment]
allright thank you for alerting me on this. I develop on OSX as this tool is majorly focused on OSX so i dont notice when after some commits it stops working on windows. I will get on my windows PC and fix this.

**Comment by venkata16sidhartha** [comment]
![image](https://user-images.githubusercontent.com/46317898/166109901-5c10e7fe-c28f-412f-ac60-f10f14db4b4f.png)
so in this image, ignore the already in use thing,
the first shell created is on sme system, where i ran the obfuscated python code, and hence shell is created on same system, 2ns one is where i ran the same obfuscated code on my windows system, and shell is dropped

**Comment by SubGlitch1** [comment]
does running the unobfuscated script on windows work?

**Comment by venkata16sidhartha** [comment]
obfuscated script(python file) runs and creates a stable shell, but exe compiled with pyinstaller does not.

**Comment by SubGlitch1** [comment]
it must be because pyinstaller is not importing the required libaries for the frozen python interpreter which is used in the .exe

**Comment by venkata16sidhartha** [comment]
could you help me how to do it, as now, i have a fully FUD py script, which is really awesome

**Comment by SubGlitch1** [comment]
thank you and also i will hekp you brother dont worry.

first of all can you compile the script with this command:
pyinstaller -F --hidden-import imp --hidden-import socket --hidden-import urllib3 ocr_or.py

**Comment by venkata16sidhartha** [comment]
im adding a -w as well in the above command

**Comment by SubGlitch1** [comment]
waiiiit i am so stupid

**Comment by SubGlitch1** [comment]
can you try this pyinstaller -F --hidden-import zlib --hidden-import socket --hidden-import base64 ocr_or.py

**Comment by venkata16sidhartha** [comment]
![image](https://user-images.githubusercontent.com/46317898/166110589-635a6589-a01b-4051-ad74-f6d6338a80af.png)

**Comment by SubGlitch1** [comment]
Allright give me 30 minutes or so

**Comment by venkata16sidhartha** [comment]
Please take your time, no hurry.

**Comment by venkata16sidhartha** [comment]
Additionally, please look into the obfuscation, virustotal is picking this up.

**Comment by SubGlitch1** [comment]
yeah if u look at the wiki u can see that this is only FUD for macOS

**Comment by SubGlitch1** [comment]
i think i will discontinue windows support for now until this issue is fixed

**Comment by venkata16sidhartha** [comment]
ok, looking forward for it.

**Comment by SubGlitch1** [comment]
i will thank you for bringing this issue to my attention
