### ISSUE TITLE
Readme for Mac paylaods

### ISSUE THREAD

**Issue by venkata16sidhartha** [SubGlitch1/OSRipper#11]
Could you please provide a writeup to create mac payloads, as the code is generating .exe alone.

Apologies for being a noob in Mac.

**Comment by SubGlitch1** [comment]
Python code is universal meaning u can develop on e.g. macOS and run on windows. When you compile it however it turns it into a binary (on windows this would be a .exe for example). You cannot create mac backdoors (at least not any compiled ones) from windows. You can also not create .exes from linux or macOS. 
You can however run macOS compiled executables (which are calles unix executables) on Linux and linux compiled executables on macOS. So just run OSRipper as you would on windows on a linux machine or a macOS machine and u would acomplish this.

**Comment by SubGlitch1** [comment]
Apologies if you did not understand that here is an article explaining it
https://github.com/pyinstaller/pyinstaller/issues/2613

**Comment by SubGlitch1** [comment]
also if you are interested on the way it functions 
https://github.com/SubGlitch1/OSRipper/wiki

**Comment by SubGlitch1** [comment]
If anything seems unclear don't hesitate to ask

**Comment by SubGlitch1** [comment]
if that is all i am closing this issue now
