### ISSUE TITLE
Miner Build Error

### ISSUE THREAD

**Issue by MikeyManji** [SubGlitch1/OSRipper#13]
Hello, 
I have an error when I try to build something with OSRipper...
Here are the details:

        1. Create Bind Backdoor (opens a port on the victim machine and waits for you to connect)
        2. Create Encrypted TCP Meterpreter (can embed in other script) (recommended)

        ##########################################################################################
                                                Miners
        3. Create a silent BTC miner
        

Please select a module: 3
Please enter the payout btc address: "my wallet"
Do you want to obfuscate the generated programm (recommended) (y/n): y

 [-] Encoded File Size : 56.4 KB

Do you want to compile the script into a binary (might require sudo) (y/n): y
1329 INFO: PyInstaller: 3.5+498e6ee058
1329 INFO: Python: 3.9.10
1334 INFO: Platform: Linux-5.15.0-kali3-amd64-x86_64-with-glibc2.33
1335 INFO: wrote /home/"my name"/Bureau/OSRipper/OSRipper/ocr_or.spec
1413 INFO: UPX is available.
1415 INFO: Extending PYTHONPATH with paths
['/home/"my name"/Bureau/OSRipper/OSRipper', '/home/"my name"/Bureau/OSRipper/OSRipper']
1415 INFO: checking Analysis
1427 INFO: Building Analysis because Analysis-00.toc is non existent
1428 INFO: Initializing module dependency graph...
1433 INFO: Initializing module graph hooks...
1484 INFO: Analyzing base_library.zip ...
7038 INFO: Processing pre-find module path hook   distutils
14934 INFO: Analyzing hidden import 'json'
15136 INFO: running Analysis Analysis-00.toc
15220 INFO: Caching module hooks...
15226 INFO: Analyzing /home/"my name"/Bureau/OSRipper/OSRipper/ocr_or.py
15237 INFO: Loading module hooks...
15237 INFO: Loading module hook "hook-pydoc.py"...
15289 INFO: Loading module hook "hook-xml.etree.cElementTree.py"...
15292 INFO: Loading module hook "hook-encodings.py"...
15391 INFO: Loading module hook "hook-distutils.py"...
15417 INFO: Loading module hook "hook-lib2to3.py"...
15455 INFO: Loading module hook "hook-sysconfig.py"...
15470 INFO: Loading module hook "hook-_tkinter.py"...
16094 INFO: checking Tree
16117 INFO: checking Tree
16125 INFO: Loading module hook "hook-xml.py"...
16371 INFO: Looking for ctypes DLLs
16424 INFO: Analyzing run-time hooks ...
16430 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
16458 INFO: Including run-time hook 'pyi_rth__tkinter.py'
16474 INFO: Looking for dynamic libraries
17282 INFO: Looking for eggs
17282 INFO: Python library not in binary dependencies. Doing additional searching...
Traceback (most recent call last):
  File "/usr/bin/pyinstaller", line 11, in <module>
    load_entry_point('PyInstaller==3.5+498e6ee058', 'console_scripts', 'pyinstaller')()
  File "/usr/lib/python3/dist-packages/PyInstaller/__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/usr/lib/python3/dist-packages/PyInstaller/__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/usr/lib/python3/dist-packages/PyInstaller/building/build_main.py", line 844, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/usr/lib/python3/dist-packages/PyInstaller/building/build_main.py", line 791, in build
    exec(code, spec_namespace)
  File "/home/"my name"Bureau/OSRipper/OSRipper/ocr_or.spec", line 6, in <module>
    a = Analysis(['ocr_or.py'],
  File "/usr/lib/python3/dist-packages/PyInstaller/building/build_main.py", line 243, in __init__
    self.__postinit__()
  File "/usr/lib/python3/dist-packages/PyInstaller/building/datastruct.py", line 158, in __postinit__
    self.assemble()
  File "/usr/lib/python3/dist-packages/PyInstaller/building/build_main.py", line 575, in assemble
    self._check_python_library(self.binaries)
  File "/usr/lib/python3/dist-packages/PyInstaller/building/build_main.py", line 666, in _check_python_library
    python_lib = bindepend.get_python_library_path()
  File "/usr/lib/python3/dist-packages/PyInstaller/depend/bindepend.py", line 914, in get_python_library_path
    python_libname = findLibrary(name)
  File "/usr/lib/python3/dist-packages/PyInstaller/depend/bindepend.py", line 778, in findLibrary
    utils.load_ldconfig_cache()
  File "/usr/lib/python3/dist-packages/PyInstaller/depend/utils.py", line 375, in load_ldconfig_cache
    path = m.groups()[-1]
AttributeError: 'NoneType' object has no attribute 'groups'
Saved under "dist" folder
You can monitor your `miners` here : https://solo.ckpool.org/

**Comment by SubGlitch1** [comment]
hi thank you for reporting this issue i will look into it right now another user seems to have the exact same error

**Comment by SubGlitch1** [comment]
[https://github.com/pyinstaller/pyinstaller/issues/4643#issuecomment-583185037 ](url)
this might solve it #

**Comment by MikeyManji** [comment]
Hey thanks for your reply but I tested and isn't working...
What else can I try?

**Comment by SubGlitch1** [comment]
I can somehow not reproduce this error. It however seems to be the issue of the compiler (which some other people also have on their repo
