### ISSUE TITLE
hello  from a friend 

### ISSUE THREAD

**Issue by suject101** [SubGlitch1/OSRipper#14]
hello  man  nothing  too  serious   project  is  cool  but  i  try  to  reach  out  on  discord but  u  never  reply  hope  to  here  from you

**Comment by SubGlitch1** [comment]
Hey man I have deactivated my discord for some reasons. Thank you for reaching out to me

**Comment by suject101** [comment]
okay  cool  man  , is  there any other  way  i can reach out  to  you? send  it to  me  on  mail  if  you  there  is  one  marvez@protonmail.com
