### ISSUE TITLE
where am i ment to type "sudo python3 main.py" im new to this stuff?

### ISSUE THREAD

**Issue by Linxo-glitch** [SubGlitch1/OSRipper#19]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by SubGlitch1** [comment]
On the terminal of your computer

**Comment by Linxo-glitch** [comment]
> On the terminal of your computer

it just says this 'sudo' is not recognized as an internal or external command,
operable program or batch file.

**Comment by SubGlitch1** [comment]
So you are using windows. In that case you have to open command prompt as administrator (you can right click on it to see that option) and simply write "python3 main.py"
