### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by MrAntiAuth** [SubGlitch1/OSRipper#22]
Hello there,
i dont find the output of the files, they should be in 

Follow the steps of option 2 but with ico file added

Expected behavior:
the output binary file or exe file to be in /home/kali/Desktop/OSRipper-0.3/dist/ as usual 

Screenshots

**Desktop (please complete the following information):**
 - OS: latest kali linux dis.
 - Browser firefox
 - Version latest

Additional context
With the bitcoin miner option everything worked and i got an output in /home/kali/Desktop/OSRipper-0.3/dist/ 

Logs: 
RootKit
Do you want the backdoor to hide itself and replicate a system proccess? (OSX and linux only and doesnt support ngrok) (y/n): n
wait...
[*] Using configured payload generic/shell_reverse_tcp
payload => python/meterpreter/reverse_tcp_ssl
LHOST => 0.0.0.0
LPORT => 443
[*] Started reverse SSL handler on 0.0.0.0:443

**Comment by SubGlitch1** [comment]
Hello,
Thank you for bringing this to my attention. I'm just seeing this now and it's really late for me (long day of uni). I'd hop on and fix it if I wasn't this tired. Imma sleep a few hours and take a look at it.

**Comment by SubGlitch1** [comment]
> Hello there, i dont find the output of the files, they should be in
> 
> Steps to reproduce the behavior: Follow the steps of option 2 but with ico file added
> 
> Expected behavior: the output binary file or exe file to be in /home/kali/Desktop/OSRipper-0.3/dist/ as usual
> 
> Screenshots
> 
> **Desktop (please complete the following information):**
> 
> * OS: latest kali linux dis.
> * Browser firefox
> * Version latest
> 
> Additional context With the bitcoin miner option everything worked and i got an output in /home/kali/Desktop/OSRipper-0.3/dist/
> 
> Logs: RootKit Do you want the backdoor to hide itself and replicate a system proccess? (OSX and linux only and doesnt support ngrok) (y/n): n wait... [_] Using configured payload generic/shell_reverse_tcp payload => python/meterpreter/reverse_tcp_ssl LHOST => 0.0.0.0 LPORT => 443 [_] Started reverse SSL handler on 0.0.0.0:443

run
`sudo apt install patchelf`
and try again

**Comment by MrAntiAuth** [comment]
hmm it doesnt seem to be working after installing patchelf 
Output: 
RootKit
Do you want the backdoor to hide itself and replicate a system proccess? (OSX and linux only and doesnt support ngrok) (y/n): n
wait...
[*] Using configured payload generic/shell_reverse_tcp
payload => python/meterpreter/reverse_tcp_ssl
LHOST => 0.0.0.0
LPORT => 443
[*] Started reverse SSL handler on 0.0.0.0:443 

Do i need to install the requirements manually or do they get installed after running the setup.py script ?

**Comment by SubGlitch1** [comment]
> hmm it doesnt seem to be working after installing patchelf Output: RootKit Do you want the backdoor to hide itself and replicate a system proccess? (OSX and linux only and doesnt support ngrok) (y/n): n wait... [_] Using configured payload generic/shell_reverse_tcp payload => python/meterpreter/reverse_tcp_ssl LHOST => 0.0.0.0 LPORT => 443 [_] Started reverse SSL handler on 0.0.0.0:443
> 
> Do i need to install the requirements manually or do they get installed after running the setup.py script ?

so the setup.py file does actually install the dependencies. interesting that it doesnt work. i tried on my kali and it does. can you try running "nuitka" in your terminal?

**Comment by MrAntiAuth** [comment]
oh wait, i looked in the python code and it seems to start a webserver, maybe because i use kali as a virtual machine with NAT it cant run the webserver? i could test it out on my Kali server. It could take a moment

**Comment by SubGlitch1** [comment]
No if it's a network issue it would not affect the generation. From your output it seems like you didn't have nuitka installed before. Try again does it work after installing it?

**Comment by SubGlitch1** [comment]
Happy it works on the server. Thank you still.
