### ISSUE TITLE
wont open for me

### ISSUE THREAD

**Issue by zen1em** [SubGlitch1/OSRipper#23]
tried everything idk just closes python straight away i have latest version

**Comment by SubGlitch1** [comment]
Could you be a bit more specific? What closes Python straight away? How are you trying to run it? Which file are you trying to run? What platform are you on?

**Comment by zen1em** [comment]
windows 10 i tried all of them but yea 😪

**Comment by SubGlitch1** [comment]
> windows 10 i tried all of them but yea 😪

What command are you running to run the program?
Are you just double clicking the file? 
You actually have to start the program over the command prompt by navigating into the folder where you downloaded it to and then running python3 main.py.
Something tells me you aren't doing that

**Comment by Silentsniper1** [comment]
> windows 10 i tried all of them but yea 😪

who ever is interested send me a message on discord saying Crypter, my discord username is:Silentsniper0
