### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by Chomikmarkus** [SubGlitch1/OSRipper#3]
Hello!

When i try to generate payload with 1 option all goes good until i get option of masking payload and hiding itself!
![Screenshot_20220327-223425_JuiceSSH](https://user-images.githubusercontent.com/92059377/160297752-1d022d4a-d7a1-4ba8-a814-c66013030391.jpg)

**Comment by SubGlitch1** [comment]
hey, thank you for raising this issue.
I have fixed this problem you can clone again and it will work now

**Comment by SubGlitch1** [comment]
@Chomikmarkus feel free to close issue if you do not have any other issues
have another day (:

**Comment by SubGlitch1** [comment]
also for your information OSRipper will also generate normal unix executables but it is meant for macOS so most of the post explotation modules will fail on android probably

**Comment by Chomikmarkus** [comment]
Now im getting 
Syntax error in /opt/OSRipper/appstore
  File "/opt/OSRipper/appstore", line 19
     host = "localhost"
     ^
 IndentationError: unexpected indent

Traceback (most recent call last):
  File "main.py", line 556, in <module>
    cleanup()
  File "main.py", line 525, in cleanup
    os.remove(os.getcwd()+'/dist/ocr_or')
FileNotFoundError: [Errno 2] No such file or directory: '/opt/OSRipper/dist/ocr_or'
root@ubuntu-s-2vcpu-4gb-ams3-01:/opt/OSRipper# ls
LICENSE    SwiftBelt    appstore       appstore_or.py    build  docs  main.py        requirements.txt
README.MD  __pycache__  appstore.spec  appstore_or.spec  dist   img   obfuscator.py
root@ubuntu-s-2vcpu-4gb-ams3-01:/opt/OSRipper# cd dist
root@ubuntu-s-2vcpu-4gb-ams3-01:/opt/OSRipper/dist# ls
appstore_or
root@ubuntu-s-2vcpu-4gb-ams3-01:/opt/OSRipper/dist#

**Comment by SubGlitch1** [comment]
fixed now

**Comment by Chomikmarkus** [comment]
I am using Ubuntu 20.04 machine for compiling! Tried iut options, al are failing
aceback (most recent call last):
  File "main.py", line 567, in <module>
    rep_syst()
  File "main.py", line 392, in rep_syst
    if bind == '1':
NameError: name 'bind' is not defined

**Comment by SubGlitch1** [comment]
just to confirm you have latest commit yes?
https://github.com/SubGlitch1/OSRipper/commit/c99266ab0023031b83c1baa5d4d1e1f33cfc8670

**Comment by Chomikmarkus** [comment]
Yes

**Comment by SubGlitch1** [comment]
i have tried on 3 different machines (macOS, Windows and ubuntu) and it works on all. i think you might not have the latest version

**Comment by SubGlitch1** [comment]
> Yes

brother i do apologise it was me who made a mistake. please try again with latest version

**Comment by Chomikmarkus** [comment]
Still getting next error:
File "main.py", line 536, in <module>
    cleanup()
  File "main.py", line 511, in cleanup
    shutil.rmtree(os.getcwd()+'/dist/ocr_or.app')
  File "/usr/lib/python3.8/shutil.py", line 709, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/usr/lib/python3.8/shutil.py", line 707, in rmtree
    orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/OSRipper/dist/ocr_or.app'
root@ubuntu-s-2vcpu-4gb-ams3-01:/opt/OSRipper#

**Comment by SubGlitch1** [comment]
ah i see. this is because it is meant for macos which generates .apps. Ubuntu doesnt do this. I have made a handling for this error. Please try now

**Comment by Chomikmarkus** [comment]
![Screenshot_20220329-235018_JuiceSSH](https://user-images.githubusercontent.com/92059377/160704762-ad2deb63-c855-4956-b0f2-0c4cfca80e6d.jpg)

**Comment by SubGlitch1** [comment]
does this fix it?

**Comment by Chomikmarkus** [comment]
No i ment that it cannot find path of ocr during compilation and fails!

**Comment by SubGlitch1** [comment]
> No i ment that it cannot find path of ocr during compilation and fails!

yes it is because in OSX cleanup() firstly deletes the leftovers and then the .app so i have changed it for linux 1 minute ago

**Comment by Chomikmarkus** [comment]
Works now ;) I will test it soon on some device and keep you posted! Closing for now!
