### ISSUE TITLE
Python Error

### ISSUE THREAD

**Issue by psycho2716** [SubGlitch1/OSRipper#5]
It shows up this error even in my kali linux distro. Please help.
![Screenshot_20220330_224554_com termux](https://user-images.githubusercontent.com/78391974/160863250-ae4ff235-8e40-46b2-bbf2-fbf589b3f736.jpg)

**Comment by psycho2716** [comment]
> someone else had this error yesterday. Do you have the latest version?

Yes bro, kali 2022.1

**Comment by SubGlitch1** [comment]
> > someone else had this error yesterday. Do you have the latest version?
> 
> Yes bro, kali 2022.1, and osripper to latest version release

delete the release version and just clone it from master branch

**Comment by SubGlitch1** [comment]
im gonna go ahead and close this as this has been fixed in issue #3
