### ISSUE TITLE
Error no such file or directory /dist/oc_or

### ISSUE THREAD

**Issue by Trusthoodies** [SubGlitch1/OSRipper#7]
### Discussed in https://github.com/SubGlitch1/OSRipper/discussions/6

<div type='discussions-op-text'>

<sup>Originally posted by **Trusthoodies** April  2, 2022</sup>
I get the error on different linux systems.
The error is: No such file or directory: /Home/OSRipper/ocr_or</div>
i cloned the github in my linux system

**Comment by SubGlitch1** [comment]
can you please tell me which options you used and copy+paste the exact error. Thank you

**Comment by Trusthoodies** [comment]
Thanks for the reply! I got the same error as psycho2712. He also started a discussion 5 daya ago. It doesnt matter wich option i choose.

**Comment by Trusthoodies** [comment]
![image](https://user-images.githubusercontent.com/95029137/161388147-8ae4d451-6227-49b3-b328-7b681a7e2714.jpeg)

**Comment by Trusthoodies** [comment]
![afbeelding](https://user-images.githubusercontent.com/95029137/161389942-d53b35eb-1dfd-4e49-b7aa-eee89f609970.png)

**Comment by SubGlitch1** [comment]
hey, thank you for your detailed report. this seems to be the same issue as this https://github.com/SubGlitch1/OSRipper/issues/3

this error arises because originally i have made this program to be run on macOS which has a different way of compiling than linux. I have fixed it i think it should work not. Please clone again and let me know

**Comment by Trusthoodies** [comment]
It worked! thank you very much!.

**Comment by Trusthoodies** [comment]
Now i have another problem, i filled in the right ip address and port but i don't see anything if i run it on my other laptop in the same network. Do you know what this can be? and does it support nrok?

**Comment by SubGlitch1** [comment]
u must have selected the replication and trojanisation option. That is only available for macos machines for now. Please deselect that option, generate a new one and let me know how it goes

**Comment by Trusthoodies** [comment]
Do you mean the obfuscate option? i didnt select that, im using a windows machine for the target. im using option 4 the encrypted tcp.

**Comment by SubGlitch1** [comment]
> Do you mean the obfuscate option? i didnt select that, im using a windows machine for the target. im using option 4 the encrypted tcp. it doesnt work
hahahahah i understand now. I have recently added a antivm detector which lowers the vt score. it seems to detect your windows machine as a vm (which is propably is) i will disable this for now and make it optional later.

**Comment by Trusthoodies** [comment]
Thank you!

**Comment by SubGlitch1** [comment]
https://github.com/SubGlitch1/OSRipper/commit/7de8867c083bd52124f737f1054151c9b92d6786

here u got brother.
Let me know how it goes

**Comment by Trusthoodies** [comment]
Thank you for the fast reply!  unfortunately he doesn't yet. I have not selected the obfuscate option. I also wanted to test the bind option and it doesn't work either.

**Comment by SubGlitch1** [comment]
This is very strange as it works for me. I will setup a virtual windows machine and test.

**Comment by Trusthoodies** [comment]
Thanks! Did you test it on a vm?

**Comment by Trusthoodies** [comment]
It still doesnt work for me

**Comment by Trusthoodies** [comment]
Do you maybe have discord or something?

**Comment by SubGlitch1** [comment]
> Thanks! Did you test it on a vm?

i am busy with a project for university right now which is due tomorow. After tomorow however i plan on heavily developing this so do not worry

**Comment by Trusthoodies** [comment]
Thanks! Goodluck with your project!

**Comment by SubGlitch1** [comment]
hey brother. I have just properly thought about this. If you generate on linux that means that you cannot compile an .exe so that means u must be running it on python on the windows host. That machine probably does not have the dependencies and the program is therefore not running. If you choose to compile it the dependencies will be in the backdoor itself.

**Comment by Trusthoodies** [comment]
So you tink i need to run this on a Windows machine and then it will work?

**Comment by SubGlitch1** [comment]
yeah just compile it. You can also try it on linux. But obv you have yo compile it on the same OS as the target system

**Comment by Trusthoodies** [comment]
Thanks i will give it a try!

**Comment by SubGlitch1** [comment]
> Thanks i will give it a try!

pls let me know. Also to answer your question no, I have stopped using discord after getting banned 6 times in a row.

**Comment by Trusthoodies** [comment]
The obfuscate funtion doesnt work on windows, i got the error OSRipper-0.2.1/dist/ocr_or doesnt exist

**Comment by SubGlitch1** [comment]
hey bro thank you for ur patience. I have partitioned my PC and am now running a windows instance. I will make fix this and notify you here when it is done. Thank you for your help. i do appreciate it

**Comment by SubGlitch1** [comment]
> The obfuscate funtion doesnt work on windows, i got the error OSRipper-0.2.1/dist/ocr_or doesnt exist

this commit might have fixed it brother

**Comment by Trusthoodies** [comment]
I tested it this morning on my Windows pc but i got this error:
![afbeelding](https://user-images.githubusercontent.com/95029137/161924759-4f9c5e77-b181-4628-b0bc-d0b28e1ffb32.png)

**Comment by Trusthoodies** [comment]
Thanks! i will test it today! Is the OSRipper also compitable with NROK?

**Comment by SubGlitch1** [comment]
> Thanks! i will test it today! Is the OSRipper also compitable with NROK?

i am developing version 2.3 rn. I will probably integrate tor hidden services because it is more anonymous and it does not require port forwarding

**Comment by SubGlitch1** [comment]
you need to add it to path. 
https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/
just put the metasploit directory here

**Comment by Trusthoodies** [comment]
Hello, Thanks for you help! i came alot further. But now when i open it on my other Windows client i get the following "Error" 
I made the .py file to exe with auto-py-to-exe
![afbeelding](https://user-images.githubusercontent.com/95029137/162273790-680f6c74-1c74-4f17-91c6-596d10bae83e.png)

**Comment by Trusthoodies** [comment]
And it is stuck on sending stage.

**Comment by SubGlitch1** [comment]
why are you compiling it manually?

**Comment by SubGlitch1** [comment]
osripper has a option for that you need to use that.

**Comment by Trusthoodies** [comment]
Which option is that? I dont see thst option, im sorry if i sound dumb but i can t see that option.

**Comment by SubGlitch1** [comment]
dont worry my friend it happens to the best of us. this is the option 
'Do you want to compile the script into a binary'
Just choose y here

**Comment by SubGlitch1** [comment]
this should have solved your issue i will close now
