### ISSUE TITLE
Dist Folder Empty

### ISSUE THREAD

**Issue by psycho2716** [SubGlitch1/OSRipper#9]
Generated in dist
OSRipper will now wait for the Victim to launch the Backdoor. As soon as they do you will see a file called output.txt with all the data that has been pulled of the target
After that the listener will spawn instantly

 Server is listening on port : 9898

Dist Folder is empty after backdoor has been created successfully.

**Comment by SubGlitch1** [comment]
hey bro thank you for opening this issue.
Which OS do you use and which options did u choose?

**Comment by psycho2716** [comment]
> hey bro thank you for opening this issue. Which OS do you use and which options did u choose?

I used Kali Linux 2022.1 bro

**Comment by SubGlitch1** [comment]
should be fixed by now bro please try again
